// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DB.proto

#include "DB.pb.h"
#include "DB.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace DB {

static const char* DB_method_names[] = {
  "/DB.DB/CreateUser",
  "/DB.DB/DeleteUser",
  "/DB.DB/UpdateUser",
  "/DB.DB/GetUser",
};

std::unique_ptr< DB::Stub> DB::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DB::Stub> stub(new DB::Stub(channel, options));
  return stub;
}

DB::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateUser_(DB_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteUser_(DB_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUser_(DB_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUser_(DB_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DB::Stub::CreateUser(::grpc::ClientContext* context, const ::DB::CreateUserRequest& request, ::DB::CreateUserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DB::CreateUserRequest, ::DB::CreateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateUser_, context, request, response);
}

void DB::Stub::async::CreateUser(::grpc::ClientContext* context, const ::DB::CreateUserRequest* request, ::DB::CreateUserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DB::CreateUserRequest, ::DB::CreateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, std::move(f));
}

void DB::Stub::async::CreateUser(::grpc::ClientContext* context, const ::DB::CreateUserRequest* request, ::DB::CreateUserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DB::CreateUserReply>* DB::Stub::PrepareAsyncCreateUserRaw(::grpc::ClientContext* context, const ::DB::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DB::CreateUserReply, ::DB::CreateUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DB::CreateUserReply>* DB::Stub::AsyncCreateUserRaw(::grpc::ClientContext* context, const ::DB::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DB::Stub::DeleteUser(::grpc::ClientContext* context, const ::DB::DeleteUserRequest& request, ::DB::DeleteUserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DB::DeleteUserRequest, ::DB::DeleteUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteUser_, context, request, response);
}

void DB::Stub::async::DeleteUser(::grpc::ClientContext* context, const ::DB::DeleteUserRequest* request, ::DB::DeleteUserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DB::DeleteUserRequest, ::DB::DeleteUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteUser_, context, request, response, std::move(f));
}

void DB::Stub::async::DeleteUser(::grpc::ClientContext* context, const ::DB::DeleteUserRequest* request, ::DB::DeleteUserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DB::DeleteUserReply>* DB::Stub::PrepareAsyncDeleteUserRaw(::grpc::ClientContext* context, const ::DB::DeleteUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DB::DeleteUserReply, ::DB::DeleteUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DB::DeleteUserReply>* DB::Stub::AsyncDeleteUserRaw(::grpc::ClientContext* context, const ::DB::DeleteUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DB::Stub::UpdateUser(::grpc::ClientContext* context, const ::DB::UpdateUserRequest& request, ::DB::UpdateUserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DB::UpdateUserRequest, ::DB::UpdateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUser_, context, request, response);
}

void DB::Stub::async::UpdateUser(::grpc::ClientContext* context, const ::DB::UpdateUserRequest* request, ::DB::UpdateUserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DB::UpdateUserRequest, ::DB::UpdateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUser_, context, request, response, std::move(f));
}

void DB::Stub::async::UpdateUser(::grpc::ClientContext* context, const ::DB::UpdateUserRequest* request, ::DB::UpdateUserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DB::UpdateUserReply>* DB::Stub::PrepareAsyncUpdateUserRaw(::grpc::ClientContext* context, const ::DB::UpdateUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DB::UpdateUserReply, ::DB::UpdateUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DB::UpdateUserReply>* DB::Stub::AsyncUpdateUserRaw(::grpc::ClientContext* context, const ::DB::UpdateUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DB::Stub::GetUser(::grpc::ClientContext* context, const ::DB::GetUserRequest& request, ::DB::GetUserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DB::GetUserRequest, ::DB::GetUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUser_, context, request, response);
}

void DB::Stub::async::GetUser(::grpc::ClientContext* context, const ::DB::GetUserRequest* request, ::DB::GetUserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DB::GetUserRequest, ::DB::GetUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUser_, context, request, response, std::move(f));
}

void DB::Stub::async::GetUser(::grpc::ClientContext* context, const ::DB::GetUserRequest* request, ::DB::GetUserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DB::GetUserReply>* DB::Stub::PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::DB::GetUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DB::GetUserReply, ::DB::GetUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DB::GetUserReply>* DB::Stub::AsyncGetUserRaw(::grpc::ClientContext* context, const ::DB::GetUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

DB::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DB_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DB::Service, ::DB::CreateUserRequest, ::DB::CreateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DB::CreateUserRequest* req,
             ::DB::CreateUserReply* resp) {
               return service->CreateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DB_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DB::Service, ::DB::DeleteUserRequest, ::DB::DeleteUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DB::DeleteUserRequest* req,
             ::DB::DeleteUserReply* resp) {
               return service->DeleteUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DB_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DB::Service, ::DB::UpdateUserRequest, ::DB::UpdateUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DB::UpdateUserRequest* req,
             ::DB::UpdateUserReply* resp) {
               return service->UpdateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DB_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DB::Service, ::DB::GetUserRequest, ::DB::GetUserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DB::GetUserRequest* req,
             ::DB::GetUserReply* resp) {
               return service->GetUser(ctx, req, resp);
             }, this)));
}

DB::Service::~Service() {
}

::grpc::Status DB::Service::CreateUser(::grpc::ServerContext* context, const ::DB::CreateUserRequest* request, ::DB::CreateUserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DB::Service::DeleteUser(::grpc::ServerContext* context, const ::DB::DeleteUserRequest* request, ::DB::DeleteUserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DB::Service::UpdateUser(::grpc::ServerContext* context, const ::DB::UpdateUserRequest* request, ::DB::UpdateUserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DB::Service::GetUser(::grpc::ServerContext* context, const ::DB::GetUserRequest* request, ::DB::GetUserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace DB

