// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DB.proto
// Protobuf C++ Version: 5.29.5

#include "DB.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace DB {

inline constexpr UpdateUserRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        level_{0u},
        hp_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateUserRequest::UpdateUserRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateUserRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateUserRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateUserRequestDefaultTypeInternal() {}
  union {
    UpdateUserRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateUserRequestDefaultTypeInternal _UpdateUserRequest_default_instance_;

inline constexpr UpdateUserReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        level_{0u},
        hp_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateUserReply::UpdateUserReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateUserReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateUserReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateUserReplyDefaultTypeInternal() {}
  union {
    UpdateUserReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateUserReplyDefaultTypeInternal _UpdateUserReply_default_instance_;

inline constexpr GetUserRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetUserRequest::GetUserRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetUserRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetUserRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetUserRequestDefaultTypeInternal() {}
  union {
    GetUserRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetUserRequestDefaultTypeInternal _GetUserRequest_default_instance_;

inline constexpr GetUserReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        level_{0u},
        hp_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetUserReply::GetUserReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetUserReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetUserReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetUserReplyDefaultTypeInternal() {}
  union {
    GetUserReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetUserReplyDefaultTypeInternal _GetUserReply_default_instance_;

inline constexpr DeleteUserRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DeleteUserRequest::DeleteUserRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeleteUserRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteUserRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteUserRequestDefaultTypeInternal() {}
  union {
    DeleteUserRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteUserRequestDefaultTypeInternal _DeleteUserRequest_default_instance_;

inline constexpr DeleteUserReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DeleteUserReply::DeleteUserReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeleteUserReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteUserReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteUserReplyDefaultTypeInternal() {}
  union {
    DeleteUserReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteUserReplyDefaultTypeInternal _DeleteUserReply_default_instance_;

inline constexpr CreateUserRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CreateUserRequest::CreateUserRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateUserRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateUserRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateUserRequestDefaultTypeInternal() {}
  union {
    CreateUserRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateUserRequestDefaultTypeInternal _CreateUserRequest_default_instance_;

inline constexpr CreateUserReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CreateUserReply::CreateUserReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateUserReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateUserReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateUserReplyDefaultTypeInternal() {}
  union {
    CreateUserReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateUserReplyDefaultTypeInternal _CreateUserReply_default_instance_;
}  // namespace DB
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_DB_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_DB_2eproto = nullptr;
const ::uint32_t
    TableStruct_DB_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::CreateUserRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::CreateUserRequest, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::CreateUserReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::CreateUserReply, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::DeleteUserRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::DeleteUserRequest, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::DeleteUserReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::DeleteUserReply, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserRequest, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserRequest, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserRequest, _impl_.hp_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserReply, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserReply, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::DB::UpdateUserReply, _impl_.hp_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::GetUserRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::GetUserRequest, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DB::GetUserReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DB::GetUserReply, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::DB::GetUserReply, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::DB::GetUserReply, _impl_.hp_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::DB::CreateUserRequest)},
        {9, -1, -1, sizeof(::DB::CreateUserReply)},
        {18, -1, -1, sizeof(::DB::DeleteUserRequest)},
        {27, -1, -1, sizeof(::DB::DeleteUserReply)},
        {36, -1, -1, sizeof(::DB::UpdateUserRequest)},
        {47, -1, -1, sizeof(::DB::UpdateUserReply)},
        {58, -1, -1, sizeof(::DB::GetUserRequest)},
        {67, -1, -1, sizeof(::DB::GetUserReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::DB::_CreateUserRequest_default_instance_._instance,
    &::DB::_CreateUserReply_default_instance_._instance,
    &::DB::_DeleteUserRequest_default_instance_._instance,
    &::DB::_DeleteUserReply_default_instance_._instance,
    &::DB::_UpdateUserRequest_default_instance_._instance,
    &::DB::_UpdateUserReply_default_instance_._instance,
    &::DB::_GetUserRequest_default_instance_._instance,
    &::DB::_GetUserReply_default_instance_._instance,
};
const char descriptor_table_protodef_DB_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\010DB.proto\022\002DB\"\037\n\021CreateUserRequest\022\n\n\002I"
    "D\030\001 \001(\004\"\"\n\017CreateUserReply\022\017\n\007message\030\001 "
    "\001(\t\"\037\n\021DeleteUserRequest\022\n\n\002ID\030\001 \001(\004\"\035\n\017"
    "DeleteUserReply\022\n\n\002ID\030\001 \001(\004\":\n\021UpdateUse"
    "rRequest\022\n\n\002ID\030\001 \001(\004\022\r\n\005level\030\002 \001(\r\022\n\n\002h"
    "p\030\003 \001(\r\"8\n\017UpdateUserReply\022\n\n\002ID\030\001 \001(\004\022\r"
    "\n\005level\030\002 \001(\r\022\n\n\002hp\030\003 \001(\r\"\034\n\016GetUserRequ"
    "est\022\n\n\002ID\030\001 \001(\004\"5\n\014GetUserReply\022\n\n\002ID\030\001 "
    "\001(\004\022\r\n\005level\030\002 \001(\r\022\n\n\002hp\030\003 \001(\r2\343\001\n\002DB\0228\n"
    "\nCreateUser\022\025.DB.CreateUserRequest\032\023.DB."
    "CreateUserReply\0228\n\nDeleteUser\022\025.DB.Delet"
    "eUserRequest\032\023.DB.DeleteUserReply\0228\n\nUpd"
    "ateUser\022\025.DB.UpdateUserRequest\032\023.DB.Upda"
    "teUserReply\022/\n\007GetUser\022\022.DB.GetUserReque"
    "st\032\020.DB.GetUserReplyB\014\252\002\trpcClientb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_DB_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_DB_2eproto = {
    false,
    false,
    602,
    descriptor_table_protodef_DB_2eproto,
    "DB.proto",
    &descriptor_table_DB_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_DB_2eproto::offsets,
    file_level_enum_descriptors_DB_2eproto,
    file_level_service_descriptors_DB_2eproto,
};
namespace DB {
// ===================================================================

class CreateUserRequest::_Internal {
 public:
};

CreateUserRequest::CreateUserRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.CreateUserRequest)
}
CreateUserRequest::CreateUserRequest(
    ::google::protobuf::Arena* arena, const CreateUserRequest& from)
    : CreateUserRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CreateUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CreateUserRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
CreateUserRequest::~CreateUserRequest() {
  // @@protoc_insertion_point(destructor:DB.CreateUserRequest)
  SharedDtor(*this);
}
inline void CreateUserRequest::SharedDtor(MessageLite& self) {
  CreateUserRequest& this_ = static_cast<CreateUserRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CreateUserRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CreateUserRequest(arena);
}
constexpr auto CreateUserRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CreateUserRequest),
                                            alignof(CreateUserRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CreateUserRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CreateUserRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CreateUserRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CreateUserRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CreateUserRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CreateUserRequest>(), &CreateUserRequest::ByteSizeLong,
            &CreateUserRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CreateUserRequest, _impl_._cached_size_),
        false,
    },
    &CreateUserRequest::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CreateUserRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CreateUserRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::CreateUserRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CreateUserRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CreateUserRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(CreateUserRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CreateUserRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.CreateUserRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CreateUserRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CreateUserRequest& this_ = static_cast<const CreateUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CreateUserRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CreateUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.CreateUserRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.CreateUserRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CreateUserRequest::ByteSizeLong(const MessageLite& base) {
          const CreateUserRequest& this_ = static_cast<const CreateUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CreateUserRequest::ByteSizeLong() const {
          const CreateUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.CreateUserRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CreateUserRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateUserRequest*>(&to_msg);
  auto& from = static_cast<const CreateUserRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.CreateUserRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateUserRequest::CopyFrom(const CreateUserRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.CreateUserRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateUserRequest::InternalSwap(CreateUserRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata CreateUserRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CreateUserReply::_Internal {
 public:
};

CreateUserReply::CreateUserReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.CreateUserReply)
}
inline PROTOBUF_NDEBUG_INLINE CreateUserReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::DB::CreateUserReply& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CreateUserReply::CreateUserReply(
    ::google::protobuf::Arena* arena,
    const CreateUserReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateUserReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:DB.CreateUserReply)
}
inline PROTOBUF_NDEBUG_INLINE CreateUserReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CreateUserReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CreateUserReply::~CreateUserReply() {
  // @@protoc_insertion_point(destructor:DB.CreateUserReply)
  SharedDtor(*this);
}
inline void CreateUserReply::SharedDtor(MessageLite& self) {
  CreateUserReply& this_ = static_cast<CreateUserReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CreateUserReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CreateUserReply(arena);
}
constexpr auto CreateUserReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateUserReply),
                                            alignof(CreateUserReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CreateUserReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CreateUserReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CreateUserReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CreateUserReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CreateUserReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CreateUserReply>(), &CreateUserReply::ByteSizeLong,
            &CreateUserReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CreateUserReply, _impl_._cached_size_),
        false,
    },
    &CreateUserReply::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CreateUserReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> CreateUserReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::CreateUserReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CreateUserReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(CreateUserReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "DB.CreateUserReply"
    "message"
  }},
};

PROTOBUF_NOINLINE void CreateUserReply::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.CreateUserReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CreateUserReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CreateUserReply& this_ = static_cast<const CreateUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CreateUserReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CreateUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.CreateUserReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DB.CreateUserReply.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.CreateUserReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CreateUserReply::ByteSizeLong(const MessageLite& base) {
          const CreateUserReply& this_ = static_cast<const CreateUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CreateUserReply::ByteSizeLong() const {
          const CreateUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.CreateUserReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CreateUserReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateUserReply*>(&to_msg);
  auto& from = static_cast<const CreateUserReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.CreateUserReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateUserReply::CopyFrom(const CreateUserReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.CreateUserReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateUserReply::InternalSwap(CreateUserReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata CreateUserReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeleteUserRequest::_Internal {
 public:
};

DeleteUserRequest::DeleteUserRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.DeleteUserRequest)
}
DeleteUserRequest::DeleteUserRequest(
    ::google::protobuf::Arena* arena, const DeleteUserRequest& from)
    : DeleteUserRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DeleteUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DeleteUserRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
DeleteUserRequest::~DeleteUserRequest() {
  // @@protoc_insertion_point(destructor:DB.DeleteUserRequest)
  SharedDtor(*this);
}
inline void DeleteUserRequest::SharedDtor(MessageLite& self) {
  DeleteUserRequest& this_ = static_cast<DeleteUserRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DeleteUserRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DeleteUserRequest(arena);
}
constexpr auto DeleteUserRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DeleteUserRequest),
                                            alignof(DeleteUserRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DeleteUserRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DeleteUserRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DeleteUserRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DeleteUserRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DeleteUserRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DeleteUserRequest>(), &DeleteUserRequest::ByteSizeLong,
            &DeleteUserRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DeleteUserRequest, _impl_._cached_size_),
        false,
    },
    &DeleteUserRequest::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DeleteUserRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DeleteUserRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::DeleteUserRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DeleteUserRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DeleteUserRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(DeleteUserRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DeleteUserRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.DeleteUserRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DeleteUserRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DeleteUserRequest& this_ = static_cast<const DeleteUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DeleteUserRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DeleteUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.DeleteUserRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.DeleteUserRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DeleteUserRequest::ByteSizeLong(const MessageLite& base) {
          const DeleteUserRequest& this_ = static_cast<const DeleteUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DeleteUserRequest::ByteSizeLong() const {
          const DeleteUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.DeleteUserRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DeleteUserRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DeleteUserRequest*>(&to_msg);
  auto& from = static_cast<const DeleteUserRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.DeleteUserRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteUserRequest::CopyFrom(const DeleteUserRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.DeleteUserRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeleteUserRequest::InternalSwap(DeleteUserRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata DeleteUserRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeleteUserReply::_Internal {
 public:
};

DeleteUserReply::DeleteUserReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.DeleteUserReply)
}
DeleteUserReply::DeleteUserReply(
    ::google::protobuf::Arena* arena, const DeleteUserReply& from)
    : DeleteUserReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DeleteUserReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DeleteUserReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
DeleteUserReply::~DeleteUserReply() {
  // @@protoc_insertion_point(destructor:DB.DeleteUserReply)
  SharedDtor(*this);
}
inline void DeleteUserReply::SharedDtor(MessageLite& self) {
  DeleteUserReply& this_ = static_cast<DeleteUserReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DeleteUserReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DeleteUserReply(arena);
}
constexpr auto DeleteUserReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DeleteUserReply),
                                            alignof(DeleteUserReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DeleteUserReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DeleteUserReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DeleteUserReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DeleteUserReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DeleteUserReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DeleteUserReply>(), &DeleteUserReply::ByteSizeLong,
            &DeleteUserReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DeleteUserReply, _impl_._cached_size_),
        false,
    },
    &DeleteUserReply::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DeleteUserReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DeleteUserReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::DeleteUserReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DeleteUserReply, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DeleteUserReply, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(DeleteUserReply, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DeleteUserReply::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.DeleteUserReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DeleteUserReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DeleteUserReply& this_ = static_cast<const DeleteUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DeleteUserReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DeleteUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.DeleteUserReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.DeleteUserReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DeleteUserReply::ByteSizeLong(const MessageLite& base) {
          const DeleteUserReply& this_ = static_cast<const DeleteUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DeleteUserReply::ByteSizeLong() const {
          const DeleteUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.DeleteUserReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DeleteUserReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DeleteUserReply*>(&to_msg);
  auto& from = static_cast<const DeleteUserReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.DeleteUserReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteUserReply::CopyFrom(const DeleteUserReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.DeleteUserReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeleteUserReply::InternalSwap(DeleteUserReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata DeleteUserReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateUserRequest::_Internal {
 public:
};

UpdateUserRequest::UpdateUserRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.UpdateUserRequest)
}
UpdateUserRequest::UpdateUserRequest(
    ::google::protobuf::Arena* arena, const UpdateUserRequest& from)
    : UpdateUserRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UpdateUserRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, hp_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::hp_));
}
UpdateUserRequest::~UpdateUserRequest() {
  // @@protoc_insertion_point(destructor:DB.UpdateUserRequest)
  SharedDtor(*this);
}
inline void UpdateUserRequest::SharedDtor(MessageLite& self) {
  UpdateUserRequest& this_ = static_cast<UpdateUserRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* UpdateUserRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateUserRequest(arena);
}
constexpr auto UpdateUserRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateUserRequest),
                                            alignof(UpdateUserRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateUserRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateUserRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateUserRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateUserRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateUserRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateUserRequest>(), &UpdateUserRequest::ByteSizeLong,
            &UpdateUserRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_._cached_size_),
        false,
    },
    &UpdateUserRequest::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateUserRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> UpdateUserRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::UpdateUserRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UpdateUserRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.id_)}},
    // uint32 level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateUserRequest, _impl_.level_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.level_)}},
    // uint32 hp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateUserRequest, _impl_.hp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.hp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 level = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 hp = 3;
    {PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.hp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UpdateUserRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.UpdateUserRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.hp_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.hp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateUserRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateUserRequest& this_ = static_cast<const UpdateUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateUserRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.UpdateUserRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          // uint32 level = 2;
          if (this_._internal_level() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_level(), target);
          }

          // uint32 hp = 3;
          if (this_._internal_hp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_hp(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.UpdateUserRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateUserRequest::ByteSizeLong(const MessageLite& base) {
          const UpdateUserRequest& this_ = static_cast<const UpdateUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateUserRequest::ByteSizeLong() const {
          const UpdateUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.UpdateUserRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // uint32 level = 2;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_level());
            }
            // uint32 hp = 3;
            if (this_._internal_hp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_hp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateUserRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateUserRequest*>(&to_msg);
  auto& from = static_cast<const UpdateUserRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.UpdateUserRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_hp() != 0) {
    _this->_impl_.hp_ = from._impl_.hp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateUserRequest::CopyFrom(const UpdateUserRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.UpdateUserRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateUserRequest::InternalSwap(UpdateUserRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.hp_)
      + sizeof(UpdateUserRequest::_impl_.hp_)
      - PROTOBUF_FIELD_OFFSET(UpdateUserRequest, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata UpdateUserRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateUserReply::_Internal {
 public:
};

UpdateUserReply::UpdateUserReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.UpdateUserReply)
}
UpdateUserReply::UpdateUserReply(
    ::google::protobuf::Arena* arena, const UpdateUserReply& from)
    : UpdateUserReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UpdateUserReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UpdateUserReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, hp_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::hp_));
}
UpdateUserReply::~UpdateUserReply() {
  // @@protoc_insertion_point(destructor:DB.UpdateUserReply)
  SharedDtor(*this);
}
inline void UpdateUserReply::SharedDtor(MessageLite& self) {
  UpdateUserReply& this_ = static_cast<UpdateUserReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* UpdateUserReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateUserReply(arena);
}
constexpr auto UpdateUserReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateUserReply),
                                            alignof(UpdateUserReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateUserReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateUserReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateUserReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateUserReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateUserReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateUserReply>(), &UpdateUserReply::ByteSizeLong,
            &UpdateUserReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_._cached_size_),
        false,
    },
    &UpdateUserReply::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateUserReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> UpdateUserReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::UpdateUserReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UpdateUserReply, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.id_)}},
    // uint32 level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateUserReply, _impl_.level_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.level_)}},
    // uint32 hp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateUserReply, _impl_.hp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.hp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 level = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 hp = 3;
    {PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.hp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UpdateUserReply::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.UpdateUserReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.hp_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.hp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateUserReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateUserReply& this_ = static_cast<const UpdateUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateUserReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.UpdateUserReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          // uint32 level = 2;
          if (this_._internal_level() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_level(), target);
          }

          // uint32 hp = 3;
          if (this_._internal_hp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_hp(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.UpdateUserReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateUserReply::ByteSizeLong(const MessageLite& base) {
          const UpdateUserReply& this_ = static_cast<const UpdateUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateUserReply::ByteSizeLong() const {
          const UpdateUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.UpdateUserReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // uint32 level = 2;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_level());
            }
            // uint32 hp = 3;
            if (this_._internal_hp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_hp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateUserReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateUserReply*>(&to_msg);
  auto& from = static_cast<const UpdateUserReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.UpdateUserReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_hp() != 0) {
    _this->_impl_.hp_ = from._impl_.hp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateUserReply::CopyFrom(const UpdateUserReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.UpdateUserReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateUserReply::InternalSwap(UpdateUserReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.hp_)
      + sizeof(UpdateUserReply::_impl_.hp_)
      - PROTOBUF_FIELD_OFFSET(UpdateUserReply, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata UpdateUserReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetUserRequest::_Internal {
 public:
};

GetUserRequest::GetUserRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.GetUserRequest)
}
GetUserRequest::GetUserRequest(
    ::google::protobuf::Arena* arena, const GetUserRequest& from)
    : GetUserRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetUserRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetUserRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
GetUserRequest::~GetUserRequest() {
  // @@protoc_insertion_point(destructor:DB.GetUserRequest)
  SharedDtor(*this);
}
inline void GetUserRequest::SharedDtor(MessageLite& self) {
  GetUserRequest& this_ = static_cast<GetUserRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GetUserRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetUserRequest(arena);
}
constexpr auto GetUserRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetUserRequest),
                                            alignof(GetUserRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetUserRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetUserRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetUserRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetUserRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetUserRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetUserRequest>(), &GetUserRequest::ByteSizeLong,
            &GetUserRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetUserRequest, _impl_._cached_size_),
        false,
    },
    &GetUserRequest::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetUserRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetUserRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::GetUserRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetUserRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetUserRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(GetUserRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetUserRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.GetUserRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetUserRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetUserRequest& this_ = static_cast<const GetUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetUserRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.GetUserRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.GetUserRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetUserRequest::ByteSizeLong(const MessageLite& base) {
          const GetUserRequest& this_ = static_cast<const GetUserRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetUserRequest::ByteSizeLong() const {
          const GetUserRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.GetUserRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetUserRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetUserRequest*>(&to_msg);
  auto& from = static_cast<const GetUserRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.GetUserRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetUserRequest::CopyFrom(const GetUserRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.GetUserRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetUserRequest::InternalSwap(GetUserRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata GetUserRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetUserReply::_Internal {
 public:
};

GetUserReply::GetUserReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DB.GetUserReply)
}
GetUserReply::GetUserReply(
    ::google::protobuf::Arena* arena, const GetUserReply& from)
    : GetUserReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetUserReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetUserReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, hp_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::hp_));
}
GetUserReply::~GetUserReply() {
  // @@protoc_insertion_point(destructor:DB.GetUserReply)
  SharedDtor(*this);
}
inline void GetUserReply::SharedDtor(MessageLite& self) {
  GetUserReply& this_ = static_cast<GetUserReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GetUserReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetUserReply(arena);
}
constexpr auto GetUserReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetUserReply),
                                            alignof(GetUserReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetUserReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetUserReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetUserReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetUserReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetUserReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetUserReply>(), &GetUserReply::ByteSizeLong,
            &GetUserReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_._cached_size_),
        false,
    },
    &GetUserReply::kDescriptorMethods,
    &descriptor_table_DB_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetUserReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> GetUserReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DB::GetUserReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 ID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetUserReply, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.id_)}},
    // uint32 level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetUserReply, _impl_.level_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.level_)}},
    // uint32 hp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetUserReply, _impl_.hp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.hp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 ID = 1;
    {PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 level = 2;
    {PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 hp = 3;
    {PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.hp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetUserReply::Clear() {
// @@protoc_insertion_point(message_clear_start:DB.GetUserReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.hp_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.hp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetUserReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetUserReply& this_ = static_cast<const GetUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetUserReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:DB.GetUserReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 ID = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          // uint32 level = 2;
          if (this_._internal_level() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_level(), target);
          }

          // uint32 hp = 3;
          if (this_._internal_hp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_hp(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:DB.GetUserReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetUserReply::ByteSizeLong(const MessageLite& base) {
          const GetUserReply& this_ = static_cast<const GetUserReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetUserReply::ByteSizeLong() const {
          const GetUserReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:DB.GetUserReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 ID = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // uint32 level = 2;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_level());
            }
            // uint32 hp = 3;
            if (this_._internal_hp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_hp());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetUserReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetUserReply*>(&to_msg);
  auto& from = static_cast<const GetUserReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DB.GetUserReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_hp() != 0) {
    _this->_impl_.hp_ = from._impl_.hp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetUserReply::CopyFrom(const GetUserReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DB.GetUserReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetUserReply::InternalSwap(GetUserReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.hp_)
      + sizeof(GetUserReply::_impl_.hp_)
      - PROTOBUF_FIELD_OFFSET(GetUserReply, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata GetUserReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DB
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_DB_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
